version: '3'

volumes:
  static_volume:
  media_volume:

services:

  web:
    build: .
    command: sh -c "gunicorn teddy_food.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static/
      - static_volume:/code/media/
    expose:
      - 8000


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - static_volume:/code/media/
    ports:
      - 80:80
    depends_on:
      - web
