# Generated by Django 3.1.3 on 2020-11-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=255, verbose_name='animal_name')),
                ('url', models.URLField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10, verbose_name='animal_sex')),
                ('favorite', models.IntegerField()),
                ('home', models.IntegerField()),
                ('take_home', models.IntegerField()),
                ('walk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='порода животного')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True, verbose_name='город приюта')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Lemmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemmas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название приюта')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='animals.animal')),
                ('lemmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='animals.lemmas')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='animals.ordernumber')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='animals.shelter')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.city'),
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.kind'),
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.shelter'),
        ),
    ]
